apiVersion: v1
kind: Service
metadata:
  name: connector
spec:
  type: LoadBalancer
  selector:
    app: connector
  ports:
    - name: http
      port: 8003
      targetPort: 8003
      protocol: TCP