apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: connector
  name: connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector
  template:
    metadata:
      labels:
        app: connector
    spec:
      containers:
      - name: connector
        image: connector:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003