apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: predictor
  name: predictor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor
        image: predictor:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8006