apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduler
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scheduler
            image: scheduler
            imagePullPolicy: Never
          restartPolicy: OnFailure